### ISSUE TITLE
multiple errors catkin build on kinetic

### ISSUE THREAD

**Issue by tzven0** [koide3/hdl_people_tracking#1]
Hello,

I'm trying to build your code with catkin build but i do get:

Starting  >>> hdl_people_tracking                                              
_______________________________________________________________________________
Errors     << hdl_people_tracking:make /home/czermak/argo/logs/hdl_people_tracking/build.make.002.log
In file included from /home/czermak/argo/src/hdl_people_tracking/apps/hdl_people_tracking_nodelet.cpp:23:0:
/home/czermak/argo/src/hdl_people_tracking/include/hdl_people_tracking/people_tracker.hpp:9:34: **fatal error: grace_msgs/Detection.h: No such file or directory**
compilation terminated.
make[2]: *** [CMakeFiles/hdl_people_tracking_nodelet.dir/apps/hdl_people_tracking_nodelet.cpp.o] Error 1
make[1]: *** [CMakeFiles/hdl_people_tracking_nodelet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/czermak/argo/src/hdl_people_tracking/apps/hdl_people_detection_nodelet.cpp:27:0:
/home/czermak/argo/src/hdl_people_tracking/include/hdl_people_detection/background_subtractor.hpp: In member function ‘visualization_msgs::MarkerConstPtr hdl_people_detection::BackgroundSubtractor::create_voxel_marker() const’:
/home/czermak/argo/src/hdl_people_tracking/include/hdl_people_detection/background_subtractor.hpp:157:68: **error: no matching function for call to ‘Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator::InnerIterator(const Eigen::SparseVector<int>&)’**
     for (Eigen::SparseVector<bool>::InnerIterator itr(occupancy_map); itr; ++itr) {
                                                                    ^
In file included from /usr/include/eigen3/Eigen/SparseCore:41:0,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /home/czermak/argo/src/hdl_people_tracking/include/hdl_people_detection/background_subtractor.hpp:5,
                 from /home/czermak/argo/src/hdl_people_tracking/apps/hdl_people_detection_nodelet.cpp:27:
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:162:26: note: candidate: template<class T> Eigen::SparseCompressedBase<Derived>::InnerIterator::InnerIterator(const Eigen::SparseMatrixBase<OtherDerived>&, Eigen::Index)
     template<typename T> InnerIterator(const SparseMatrixBase<T>&, Index outer);
                          ^
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:162:26: note:   template argument deduction/substitution failed:
In file included from /home/czermak/argo/src/hdl_people_tracking/apps/hdl_people_detection_nodelet.cpp:27:0:
/home/czermak/argo/src/hdl_people_tracking/include/hdl_people_detection/background_subtractor.hpp:157:68: note:   candidate expects 2 arguments, 1 provided
     for (Eigen::SparseVector<bool>::InnerIterator itr(occupancy_map); itr; ++itr) {
                                                                    ^
In file included from /usr/include/eigen3/Eigen/SparseCore:41:0,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /home/czermak/argo/src/hdl_people_tracking/include/hdl_people_detection/background_subtractor.hpp:5,
                 from /home/czermak/argo/src/hdl_people_tracking/apps/hdl_people_detection_nodelet.cpp:27:
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:134:14: note: candidate: Eigen::SparseCompressedBase<Derived>::InnerIterator::InnerIterator(const Eigen::internal::CompressedStorage<typename Eigen::internal::traits<Eigen::SparseCompressedBase<Derived> >::Scalar, typename Eigen::internal::traits<Eigen::SparseCompressedBase<Derived> >::StorageIndex>&) [with Derived = Eigen::SparseVector<bool>; typename Eigen::internal::traits<Eigen::SparseCompressedBase<Derived> >::StorageIndex = int; typename Eigen::internal::traits<Eigen::SparseCompressedBase<Derived> >::Scalar = bool]
     explicit InnerIterator(const internal::CompressedStorage<Scalar,StorageIndex>& data)
              ^
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:134:14: note:   no known conversion for argument 1 from ‘const Eigen::SparseVector<int>’ to ‘const Eigen::internal::CompressedStorage<bool, int>&’
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:128:14: note: candidate: Eigen::SparseCompressedBase<Derived>::InnerIterator::InnerIterator(const Eigen::SparseCompressedBase<Derived>&) [with Derived = Eigen::SparseVector<bool>]
     explicit InnerIterator(const SparseCompressedBase& mat)
              ^
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:128:14: note:   no known conversion for argument 1 from ‘const Eigen::SparseVector<int>’ to ‘const Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >&’
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:110:5: note: candidate: Eigen::SparseCompressedBase<Derived>::InnerIterator::InnerIterator(const Eigen::SparseCompressedBase<Derived>&, Eigen::Index) [with Derived = Eigen::SparseVector<bool>; Eigen::Index = long int]
     InnerIterator(const SparseCompressedBase& mat, Index outer)
     ^
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:110:5: note:   candidate expects 2 arguments, 1 provided
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:107:38: note: candidate: Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator::InnerIterator(const Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator&)
 class SparseCompressedBase<Derived>::InnerIterator
                                      ^
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:107:38: note:   no known conversion for argument 1 from ‘const Eigen::SparseVector<int>’ to ‘const Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator&’
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:107:38: note: candidate: Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator::InnerIterator(Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator&&)
/usr/include/eigen3/Eigen/src/SparseCore/SparseCompressedBase.h:107:38: note:   no known conversion for argument 1 from ‘const Eigen::SparseVector<int>’ to ‘Eigen::SparseCompressedBase<Eigen::SparseVector<bool> >::InnerIterator&&’
make[2]: *** [CMakeFiles/hdl_people_detection_nodelet.dir/apps/hdl_people_detection_nodelet.cpp.o] Error 1
make[1]: *** [CMakeFiles/hdl_people_detection_nodelet.dir/all] Error 2
make: *** [all] Error 2
cd /home/czermak/argo/build/hdl_people_tracking; catkin build --get-env hdl_people_tracking | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << hdl_people_tracking:make           [ Exited with code 2 ]        
Failed    <<< hdl_people_tracking                [ 9.2 seconds ] 

Help would be appreciated.
Thank you in advance!

**Comment by koide3** [comment]
Hi,

Thank you for your report. I didn't notice the error since I had tested it on only indigo. I'll fix the bug in a few days...

**Comment by koide3** [comment]
I fixed the errors. I think now it can be built on kinetic. Can you build it?

**Comment by tzven0** [comment]
Hey,
i only fixed the `Eigen::SparseVector<bool>` to `Eigen::SparseVector<int>` and and removed the grace_msgs include and got it to compile. Your changes are also keeping other things in mind, thank you!
