### ISSUE TITLE
ROS noetic

### ISSUE THREAD

**Issue by CDonosoK-SKG** [koide3/hdl_people_tracking#29]
Someone has build this package on ROS noetic?

**Comment by CDonosoK-SKG** [comment]
Already solve it, just need to modify the:
- CMakeList
- cvutils.cpp
- kidono_human_classifier

**Comment by domrachev03** [comment]
Faced the same problem. Could you please specify the exact adjustments to launch it on Noetic?

**Comment by TheCoolestMango** [comment]
In case anyone still has problem building this on Noetic:

1. In CMakeLists.txt lines 5-6:
```
add_definitions(-std=c++11 -msse -msse2 -msse3 -msse4 -msse4.1 -msse4.2)
set(CMAKE_CXX_FLAGS "-std=c++11 -msse -msse2 -msse3 -msse4 -msse4.1 -msse4.2") 
```
change both -std=c++11 to -std=c++14

2. cvutils.cpp (located at include/kkl/cvk) line 17:
```
cv::cvtColor(palette, palette, CV_HSV2BGR);
```
change `CV_HSV2BGR` to `cv::COLOR_HSV2BGR`

3. kidono_human_classifier.cpp (located at src/) line 21:
```
boost = cv::ml::Boost::load<cv::ml::Boost>(modelfile);
```
change to 
`boost = cv::ml::Boost::load(modelfile);`
as solved [here](https://github.com/robotics404/hdl_people_tracking/commit/ebd87b35d24e479763a443ff8d277596961fb6bd)
